BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved"
canonifyurls = true

[author]
  name = "JM"

[permalinks]
    post = "/post/:year/:month/:slug"

[params]
  description = "Just a Simple Blog"
  cover = "images/butterfly.png"
  author = "JM"
  authorlocation = ""
  bio= ""
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "J-Montgomery"
  twitterName = ""
  hideHUGOSupport = true
  mainSections = ["post"]
